"""timetable_schema

Revision ID: 9daf2fc6c73d
Revises: 0002_enable_rls
Create Date: 2026-10-06 10:15:17.401792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daf2fc6c73d'
down_revision: Union[str, Sequence[str], None] = '0002_enable_rls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('hall', sa.String(length=40), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'semester', 'effective_from')
    )
    op.create_index(op.f('ix_timetables_department_id'), 'timetables', ['department_id'], unique=False)
    op.create_table('timetable_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('after_period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_breaks_timetable_id'), 'timetable_breaks', ['timetable_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('subject_id', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('staff_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.code'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_department_id'), 'timetable_entries', ['department_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_id'), 'timetable_entries', ['timetable_id'], unique=False)
    op.create_table('timetable_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'period')
    )
    op.create_index(op.f('ix_timetable_periods_timetable_id'), 'timetable_periods', ['timetable_id'], unique=False)
    op.drop_table('timetable_slots')
    op.add_column('subjects', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('semester', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_subjects_department_id', 'subjects', 'departments', ['department_id'], ['id'])

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for table in ["timetables", "timetable_breaks", "timetable_entries", "timetable_periods"]:
            op.execute(sa.text(f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text("""
            DO $$
            BEGIN
              IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
                ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon;
              END IF;
              IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
                ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM authenticated;
              END IF;
            END $$;
        """))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_subjects_department_id', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'semester')
    op.drop_column('subjects', 'department_id')
    op.create_table('timetable_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('staff_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('timetable_slots_department_id_fkey')),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], name=op.f('timetable_slots_subject_code_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('timetable_slots_pkey'))
    )
    op.drop_index(op.f('ix_timetable_periods_timetable_id'), table_name='timetable_periods')
    op.drop_table('timetable_periods')
    op.drop_index(op.f('ix_timetable_entries_timetable_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_department_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_timetable_breaks_timetable_id'), table_name='timetable_breaks')
    op.drop_table('timetable_breaks')
    op.drop_index(op.f('ix_timetables_department_id'), table_name='timetables')
    op.drop_table('timetables')
    # ### end Alembic commands ###
