"""initial schema

Revision ID: ead8ea23334b
Revises: 
Create Date: 2026-10-05 08:24:49.471666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead8ea23334b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('result_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'semester')
    )
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('staff_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'COUNSELLOR', 'HOD', 'ADMIN', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_department_id'), 'audit_log', ['department_id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('Event', 'Circular', 'Notice', 'Exam', 'Holiday', name='noticecategory', native_enum=False, length=12), nullable=False),
    sa.Column('audience_type', sa.Enum('MY_STUDENTS', 'SELECTED_STUDENTS', 'ALL_STUDENTS', 'SECTION', 'ALL_COUNSELLORS', name='audiencetype', native_enum=False, length=20), nullable=False),
    sa.Column('audience_value', sa.String(length=60), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_author_id'), 'notices', ['author_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('register_no', sa.String(length=12), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('academic_pattern', sa.String(length=10), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('programme_code', sa.String(length=30), nullable=False),
    sa.Column('programme_name', sa.String(length=80), nullable=True),
    sa.Column('regulation_id', sa.String(length=20), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.Column('batch', sa.String(length=9), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('counsellor_id', sa.Integer(), nullable=True),
    sa.Column('photo_ref', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_dept_section', 'students', ['department_id', 'section'], unique=False)
    op.create_index(op.f('ix_students_register_no'), 'students', ['register_no'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('P', 'A', 'OD', name='attendancestatus', native_enum=False, length=4), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'on_date', 'hour')
    )
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('fee_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('fee_key', sa.String(length=40), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year', 'fee_key')
    )
    op.create_index(op.f('ix_fee_items_student_id'), 'fee_items', ['student_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('counsellor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LEAVE', 'OD', name='leavetype', native_enum=False, length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('event_name', sa.String(length=150), nullable=True),
    sa.Column('organizer', sa.String(length=150), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('letter_name', sa.String(length=120), nullable=True),
    sa.Column('letter_type', sa.String(length=40), nullable=True),
    sa.Column('letter_size', sa.Integer(), nullable=True),
    sa.Column('letter_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_COUNSELLOR', 'REJECTED_BY_COUNSELLOR', 'PENDING_HOD', 'APPROVED', 'REJECTED_BY_HOD', name='leavestatus', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['letter_file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_counsellor_id'), 'leave_requests', ['counsellor_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('cia1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('asmt1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cia2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('asmt2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'subject_code')
    )
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_table('notice_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_attachments_notice_id'), 'notice_attachments', ['notice_id'], unique=False)
    op.create_table('notice_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'user_id')
    )
    op.create_index(op.f('ix_notice_recipients_notice_id'), 'notice_recipients', ['notice_id'], unique=False)
    op.create_index(op.f('ix_notice_recipients_user_id'), 'notice_recipients', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('fee_key', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('transaction_id', sa.String(length=40), nullable=False),
    sa.Column('receipt_no', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'subject_code')
    )
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_table('leave_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('COUNSELLOR', 'HOD', name='stage', native_enum=False, length=12), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='decision', native_enum=False, length=10), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=300), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['leave_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_actions_request_id'), 'leave_actions', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_actions_request_id'), table_name='leave_actions')
    op.drop_table('leave_actions')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notice_recipients_user_id'), table_name='notice_recipients')
    op.drop_index(op.f('ix_notice_recipients_notice_id'), table_name='notice_recipients')
    op.drop_table('notice_recipients')
    op.drop_index(op.f('ix_notice_attachments_notice_id'), table_name='notice_attachments')
    op.drop_table('notice_attachments')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_counsellor_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_fee_items_student_id'), table_name='fee_items')
    op.drop_table('fee_items')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_students_register_no'), table_name='students')
    op.drop_index('ix_students_dept_section', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_notices_author_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_audit_log_department_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('timetable_slots')
    op.drop_table('result_releases')
    op.drop_table('subjects')
    op.drop_table('stored_files')
    op.drop_table('departments')
    # ### end Alembic commands ###
