/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as CampusNavigationRouteImport } from './routes/campus-navigation'
import { Route as CoeRouteImport } from './routes/coe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ErpRouteRouteImport } from './routes/erp/route'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FacultyDirectoryRouteImport } from './routes/faculty-directory'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as CoeLoginRouteImport } from './routes/coe/login'
import { Route as CoePortalRouteImport } from './routes/coe/portal'
import { Route as CoeResultsRouteImport } from './routes/coe/results'
import { Route as ErpAssignmentRouteImport } from './routes/erp/assignment'
import { Route as ErpBookVerificationFormRouteImport } from './routes/erp/book-verification-form'
import { Route as ErpDashboardRouteImport } from './routes/erp/dashboard'
import { Route as ErpFeesRouteImport } from './routes/erp/fees'
import { Route as ErpHodRouteImport } from './routes/erp/hod'
import { Route as ErpLeaveRouteImport } from './routes/erp/leave'
import { Route as ErpLeaveRequestsRouteImport } from './routes/erp/leave-requests'
import { Route as ErpLoginRouteImport } from './routes/erp.login'
import { Route as ErpNoticesRouteImport } from './routes/erp/notices'
import { Route as ErpPasswordRouteImport } from './routes/erp/password'
import { Route as ErpProfileRouteImport } from './routes/erp/profile'
import { Route as ErpResultsRouteImport } from './routes/erp/results'
import { Route as ErpStaffRouteImport } from './routes/erp/staff'
import { Route as ErpTimetableRouteImport } from './routes/erp/timetable'
import { Route as LoginHodRouteImport } from './routes/login.hod'
import { Route as LoginStaffRouteImport } from './routes/login.staff'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as ErpHodActivityRouteImport } from './routes/erp/hod.activity'
import { Route as ErpHodApprovalsRouteImport } from './routes/erp/hod.approvals'
import { Route as ErpHodReportsRouteImport } from './routes/erp/hod.reports'
import { Route as ErpHodStudentsRouteImport } from './routes/erp/hod.students'
import { Route as ErpStaffAnnouncementsRouteImport } from './routes/erp/staff.announcements'
import { Route as ErpStaffHistoryRouteImport } from './routes/erp/staff.history'
import { Route as ErpStaffLeaveRouteImport } from './routes/erp/staff.leave'
import { Route as ErpStaffStudentsRouteImport } from './routes/erp/staff.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusNavigationRoute = CampusNavigationRouteImport.update({
  id: '/campus-navigation',
  path: '/campus-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const CoeRoute = CoeRouteImport.update({
  id: '/coe',
  path: '/coe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRouteRoute = ErpRouteRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDirectoryRoute = FacultyDirectoryRouteImport.update({
  id: '/faculty-directory',
  path: '/faculty-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const CoeLoginRoute = CoeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CoeRoute,
} as any)
const CoePortalRoute = CoePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => CoeRoute,
} as any)
const CoeResultsRoute = CoeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CoeRoute,
} as any)
const ErpAssignmentRoute = ErpAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpBookVerificationFormRoute = ErpBookVerificationFormRouteImport.update({
  id: '/book-verification-form',
  path: '/book-verification-form',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpDashboardRoute = ErpDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpFeesRoute = ErpFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpHodRoute = ErpHodRouteImport.update({
  id: '/hod',
  path: '/hod',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpLeaveRoute = ErpLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpLeaveRequestsRoute = ErpLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpLoginRoute = ErpLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpNoticesRoute = ErpNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpPasswordRoute = ErpPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpProfileRoute = ErpProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpResultsRoute = ErpResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpStaffRoute = ErpStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ErpRouteRoute,
} as any)
const ErpTimetableRoute = ErpTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => ErpRouteRoute,
} as any)
const LoginHodRoute = LoginHodRouteImport.update({
  id: '/login/hod',
  path: '/login/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStaffRoute = LoginStaffRouteImport.update({
  id: '/login/staff',
  path: '/login/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpHodActivityRoute = ErpHodActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ErpHodRoute,
} as any)
const ErpHodApprovalsRoute = ErpHodApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ErpHodRoute,
} as any)
const ErpHodReportsRoute = ErpHodReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ErpHodRoute,
} as any)
const ErpHodStudentsRoute = ErpHodStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ErpHodRoute,
} as any)
const ErpStaffAnnouncementsRoute = ErpStaffAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ErpStaffRoute,
} as any)
const ErpStaffHistoryRoute = ErpStaffHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ErpStaffRoute,
} as any)
const ErpStaffLeaveRoute = ErpStaffLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ErpStaffRoute,
} as any)
const ErpStaffStudentsRoute = ErpStaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ErpStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/campus-navigation': typeof CampusNavigationRoute
  '/coe': typeof CoeRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/faculty-directory': typeof FacultyDirectoryRoute
  '/menu': typeof MenuRoute
  '/notices': typeof NoticesRoute
  '/coe/login': typeof CoeLoginRoute
  '/coe/portal': typeof CoePortalRoute
  '/coe/results': typeof CoeResultsRoute
  '/erp/assignment': typeof ErpAssignmentRoute
  '/erp/book-verification-form': typeof ErpBookVerificationFormRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/fees': typeof ErpFeesRoute
  '/erp/hod': typeof ErpHodRouteWithChildren
  '/erp/leave': typeof ErpLeaveRoute
  '/erp/leave-requests': typeof ErpLeaveRequestsRoute
  '/erp/login': typeof ErpLoginRoute
  '/erp/notices': typeof ErpNoticesRoute
  '/erp/password': typeof ErpPasswordRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/results': typeof ErpResultsRoute
  '/erp/staff': typeof ErpStaffRouteWithChildren
  '/erp/timetable': typeof ErpTimetableRoute
  '/login/hod': typeof LoginHodRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/erp/hod/activity': typeof ErpHodActivityRoute
  '/erp/hod/approvals': typeof ErpHodApprovalsRoute
  '/erp/hod/reports': typeof ErpHodReportsRoute
  '/erp/hod/students': typeof ErpHodStudentsRoute
  '/erp/staff/announcements': typeof ErpStaffAnnouncementsRoute
  '/erp/staff/history': typeof ErpStaffHistoryRoute
  '/erp/staff/leave': typeof ErpStaffLeaveRoute
  '/erp/staff/students': typeof ErpStaffStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/campus-navigation': typeof CampusNavigationRoute
  '/coe': typeof CoeRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/faculty-directory': typeof FacultyDirectoryRoute
  '/menu': typeof MenuRoute
  '/notices': typeof NoticesRoute
  '/coe/login': typeof CoeLoginRoute
  '/coe/portal': typeof CoePortalRoute
  '/coe/results': typeof CoeResultsRoute
  '/erp/assignment': typeof ErpAssignmentRoute
  '/erp/book-verification-form': typeof ErpBookVerificationFormRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/fees': typeof ErpFeesRoute
  '/erp/hod': typeof ErpHodRouteWithChildren
  '/erp/leave': typeof ErpLeaveRoute
  '/erp/leave-requests': typeof ErpLeaveRequestsRoute
  '/erp/login': typeof ErpLoginRoute
  '/erp/notices': typeof ErpNoticesRoute
  '/erp/password': typeof ErpPasswordRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/results': typeof ErpResultsRoute
  '/erp/staff': typeof ErpStaffRouteWithChildren
  '/erp/timetable': typeof ErpTimetableRoute
  '/login/hod': typeof LoginHodRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/erp/hod/activity': typeof ErpHodActivityRoute
  '/erp/hod/approvals': typeof ErpHodApprovalsRoute
  '/erp/hod/reports': typeof ErpHodReportsRoute
  '/erp/hod/students': typeof ErpHodStudentsRoute
  '/erp/staff/announcements': typeof ErpStaffAnnouncementsRoute
  '/erp/staff/history': typeof ErpStaffHistoryRoute
  '/erp/staff/leave': typeof ErpStaffLeaveRoute
  '/erp/staff/students': typeof ErpStaffStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erp': typeof ErpRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/campus': typeof CampusRoute
  '/campus-navigation': typeof CampusNavigationRoute
  '/coe': typeof CoeRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRoute
  '/faculty-directory': typeof FacultyDirectoryRoute
  '/menu': typeof MenuRoute
  '/notices': typeof NoticesRoute
  '/coe/login': typeof CoeLoginRoute
  '/coe/portal': typeof CoePortalRoute
  '/coe/results': typeof CoeResultsRoute
  '/erp/assignment': typeof ErpAssignmentRoute
  '/erp/book-verification-form': typeof ErpBookVerificationFormRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/fees': typeof ErpFeesRoute
  '/erp/hod': typeof ErpHodRouteWithChildren
  '/erp/leave': typeof ErpLeaveRoute
  '/erp/leave-requests': typeof ErpLeaveRequestsRoute
  '/erp/login': typeof ErpLoginRoute
  '/erp/notices': typeof ErpNoticesRoute
  '/erp/password': typeof ErpPasswordRoute
  '/erp/profile': typeof ErpProfileRoute
  '/erp/results': typeof ErpResultsRoute
  '/erp/staff': typeof ErpStaffRouteWithChildren
  '/erp/timetable': typeof ErpTimetableRoute
  '/login/hod': typeof LoginHodRoute
  '/login/staff': typeof LoginStaffRoute
  '/login/student': typeof LoginStudentRoute
  '/erp/hod/activity': typeof ErpHodActivityRoute
  '/erp/hod/approvals': typeof ErpHodApprovalsRoute
  '/erp/hod/reports': typeof ErpHodReportsRoute
  '/erp/hod/students': typeof ErpHodStudentsRoute
  '/erp/staff/announcements': typeof ErpStaffAnnouncementsRoute
  '/erp/staff/history': typeof ErpStaffHistoryRoute
  '/erp/staff/leave': typeof ErpStaffLeaveRoute
  '/erp/staff/students': typeof ErpStaffStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/erp'
    | '/about'
    | '/campus'
    | '/campus-navigation'
    | '/coe'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/faculty'
    | '/faculty-directory'
    | '/menu'
    | '/notices'
    | '/coe/login'
    | '/coe/portal'
    | '/coe/results'
    | '/erp/assignment'
    | '/erp/book-verification-form'
    | '/erp/dashboard'
    | '/erp/fees'
    | '/erp/hod'
    | '/erp/leave'
    | '/erp/leave-requests'
    | '/erp/login'
    | '/erp/notices'
    | '/erp/password'
    | '/erp/profile'
    | '/erp/results'
    | '/erp/staff'
    | '/erp/timetable'
    | '/login/hod'
    | '/login/staff'
    | '/login/student'
    | '/erp/hod/activity'
    | '/erp/hod/approvals'
    | '/erp/hod/reports'
    | '/erp/hod/students'
    | '/erp/staff/announcements'
    | '/erp/staff/history'
    | '/erp/staff/leave'
    | '/erp/staff/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/erp'
    | '/about'
    | '/campus'
    | '/campus-navigation'
    | '/coe'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/faculty'
    | '/faculty-directory'
    | '/menu'
    | '/notices'
    | '/coe/login'
    | '/coe/portal'
    | '/coe/results'
    | '/erp/assignment'
    | '/erp/book-verification-form'
    | '/erp/dashboard'
    | '/erp/fees'
    | '/erp/hod'
    | '/erp/leave'
    | '/erp/leave-requests'
    | '/erp/login'
    | '/erp/notices'
    | '/erp/password'
    | '/erp/profile'
    | '/erp/results'
    | '/erp/staff'
    | '/erp/timetable'
    | '/login/hod'
    | '/login/staff'
    | '/login/student'
    | '/erp/hod/activity'
    | '/erp/hod/approvals'
    | '/erp/hod/reports'
    | '/erp/hod/students'
    | '/erp/staff/announcements'
    | '/erp/staff/history'
    | '/erp/staff/leave'
    | '/erp/staff/students'
  id:
    | '__root__'
    | '/'
    | '/erp'
    | '/about'
    | '/campus'
    | '/campus-navigation'
    | '/coe'
    | '/contact'
    | '/departments'
    | '/facilities'
    | '/faculty'
    | '/faculty-directory'
    | '/menu'
    | '/notices'
    | '/coe/login'
    | '/coe/portal'
    | '/coe/results'
    | '/erp/assignment'
    | '/erp/book-verification-form'
    | '/erp/dashboard'
    | '/erp/fees'
    | '/erp/hod'
    | '/erp/leave'
    | '/erp/leave-requests'
    | '/erp/login'
    | '/erp/notices'
    | '/erp/password'
    | '/erp/profile'
    | '/erp/results'
    | '/erp/staff'
    | '/erp/timetable'
    | '/login/hod'
    | '/login/staff'
    | '/login/student'
    | '/erp/hod/activity'
    | '/erp/hod/approvals'
    | '/erp/hod/reports'
    | '/erp/hod/students'
    | '/erp/staff/announcements'
    | '/erp/staff/history'
    | '/erp/staff/leave'
    | '/erp/staff/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErpRouteRoute: typeof ErpRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CampusRoute: typeof CampusRoute
  CampusNavigationRoute: typeof CampusNavigationRoute
  CoeRoute: typeof CoeRouteWithChildren
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FacultyRoute: typeof FacultyRoute
  FacultyDirectoryRoute: typeof FacultyDirectoryRoute
  MenuRoute: typeof MenuRoute
  NoticesRoute: typeof NoticesRoute
  LoginHodRoute: typeof LoginHodRoute
  LoginStaffRoute: typeof LoginStaffRoute
  LoginStudentRoute: typeof LoginStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-navigation': {
      id: '/campus-navigation'
      path: '/campus-navigation'
      fullPath: '/campus-navigation'
      preLoaderRoute: typeof CampusNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coe': {
      id: '/coe'
      path: '/coe'
      fullPath: '/coe'
      preLoaderRoute: typeof CoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty-directory': {
      id: '/faculty-directory'
      path: '/faculty-directory'
      fullPath: '/faculty-directory'
      preLoaderRoute: typeof FacultyDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coe/login': {
      id: '/coe/login'
      path: '/login'
      fullPath: '/coe/login'
      preLoaderRoute: typeof CoeLoginRouteImport
      parentRoute: typeof CoeRoute
    }
    '/coe/portal': {
      id: '/coe/portal'
      path: '/portal'
      fullPath: '/coe/portal'
      preLoaderRoute: typeof CoePortalRouteImport
      parentRoute: typeof CoeRoute
    }
    '/coe/results': {
      id: '/coe/results'
      path: '/results'
      fullPath: '/coe/results'
      preLoaderRoute: typeof CoeResultsRouteImport
      parentRoute: typeof CoeRoute
    }
    '/erp/assignment': {
      id: '/erp/assignment'
      path: '/assignment'
      fullPath: '/erp/assignment'
      preLoaderRoute: typeof ErpAssignmentRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/book-verification-form': {
      id: '/erp/book-verification-form'
      path: '/book-verification-form'
      fullPath: '/erp/book-verification-form'
      preLoaderRoute: typeof ErpBookVerificationFormRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/dashboard': {
      id: '/erp/dashboard'
      path: '/dashboard'
      fullPath: '/erp/dashboard'
      preLoaderRoute: typeof ErpDashboardRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/fees': {
      id: '/erp/fees'
      path: '/fees'
      fullPath: '/erp/fees'
      preLoaderRoute: typeof ErpFeesRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/hod': {
      id: '/erp/hod'
      path: '/hod'
      fullPath: '/erp/hod'
      preLoaderRoute: typeof ErpHodRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/leave': {
      id: '/erp/leave'
      path: '/leave'
      fullPath: '/erp/leave'
      preLoaderRoute: typeof ErpLeaveRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/leave-requests': {
      id: '/erp/leave-requests'
      path: '/leave-requests'
      fullPath: '/erp/leave-requests'
      preLoaderRoute: typeof ErpLeaveRequestsRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/login': {
      id: '/erp/login'
      path: '/login'
      fullPath: '/erp/login'
      preLoaderRoute: typeof ErpLoginRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/notices': {
      id: '/erp/notices'
      path: '/notices'
      fullPath: '/erp/notices'
      preLoaderRoute: typeof ErpNoticesRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/password': {
      id: '/erp/password'
      path: '/password'
      fullPath: '/erp/password'
      preLoaderRoute: typeof ErpPasswordRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/profile': {
      id: '/erp/profile'
      path: '/profile'
      fullPath: '/erp/profile'
      preLoaderRoute: typeof ErpProfileRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/results': {
      id: '/erp/results'
      path: '/results'
      fullPath: '/erp/results'
      preLoaderRoute: typeof ErpResultsRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/staff': {
      id: '/erp/staff'
      path: '/staff'
      fullPath: '/erp/staff'
      preLoaderRoute: typeof ErpStaffRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/erp/timetable': {
      id: '/erp/timetable'
      path: '/timetable'
      fullPath: '/erp/timetable'
      preLoaderRoute: typeof ErpTimetableRouteImport
      parentRoute: typeof ErpRouteRoute
    }
    '/login/hod': {
      id: '/login/hod'
      path: '/login/hod'
      fullPath: '/login/hod'
      preLoaderRoute: typeof LoginHodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/staff': {
      id: '/login/staff'
      path: '/login/staff'
      fullPath: '/login/staff'
      preLoaderRoute: typeof LoginStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp/hod/activity': {
      id: '/erp/hod/activity'
      path: '/activity'
      fullPath: '/erp/hod/activity'
      preLoaderRoute: typeof ErpHodActivityRouteImport
      parentRoute: typeof ErpHodRoute
    }
    '/erp/hod/approvals': {
      id: '/erp/hod/approvals'
      path: '/approvals'
      fullPath: '/erp/hod/approvals'
      preLoaderRoute: typeof ErpHodApprovalsRouteImport
      parentRoute: typeof ErpHodRoute
    }
    '/erp/hod/reports': {
      id: '/erp/hod/reports'
      path: '/reports'
      fullPath: '/erp/hod/reports'
      preLoaderRoute: typeof ErpHodReportsRouteImport
      parentRoute: typeof ErpHodRoute
    }
    '/erp/hod/students': {
      id: '/erp/hod/students'
      path: '/students'
      fullPath: '/erp/hod/students'
      preLoaderRoute: typeof ErpHodStudentsRouteImport
      parentRoute: typeof ErpHodRoute
    }
    '/erp/staff/announcements': {
      id: '/erp/staff/announcements'
      path: '/announcements'
      fullPath: '/erp/staff/announcements'
      preLoaderRoute: typeof ErpStaffAnnouncementsRouteImport
      parentRoute: typeof ErpStaffRoute
    }
    '/erp/staff/history': {
      id: '/erp/staff/history'
      path: '/history'
      fullPath: '/erp/staff/history'
      preLoaderRoute: typeof ErpStaffHistoryRouteImport
      parentRoute: typeof ErpStaffRoute
    }
    '/erp/staff/leave': {
      id: '/erp/staff/leave'
      path: '/leave'
      fullPath: '/erp/staff/leave'
      preLoaderRoute: typeof ErpStaffLeaveRouteImport
      parentRoute: typeof ErpStaffRoute
    }
    '/erp/staff/students': {
      id: '/erp/staff/students'
      path: '/students'
      fullPath: '/erp/staff/students'
      preLoaderRoute: typeof ErpStaffStudentsRouteImport
      parentRoute: typeof ErpStaffRoute
    }
  }
}

interface ErpHodRouteChildren {
  ErpHodActivityRoute: typeof ErpHodActivityRoute
  ErpHodApprovalsRoute: typeof ErpHodApprovalsRoute
  ErpHodReportsRoute: typeof ErpHodReportsRoute
  ErpHodStudentsRoute: typeof ErpHodStudentsRoute
}

const ErpHodRouteChildren: ErpHodRouteChildren = {
  ErpHodActivityRoute: ErpHodActivityRoute,
  ErpHodApprovalsRoute: ErpHodApprovalsRoute,
  ErpHodReportsRoute: ErpHodReportsRoute,
  ErpHodStudentsRoute: ErpHodStudentsRoute,
}

const ErpHodRouteWithChildren =
  ErpHodRoute._addFileChildren(ErpHodRouteChildren)

interface ErpStaffRouteChildren {
  ErpStaffAnnouncementsRoute: typeof ErpStaffAnnouncementsRoute
  ErpStaffHistoryRoute: typeof ErpStaffHistoryRoute
  ErpStaffLeaveRoute: typeof ErpStaffLeaveRoute
  ErpStaffStudentsRoute: typeof ErpStaffStudentsRoute
}

const ErpStaffRouteChildren: ErpStaffRouteChildren = {
  ErpStaffAnnouncementsRoute: ErpStaffAnnouncementsRoute,
  ErpStaffHistoryRoute: ErpStaffHistoryRoute,
  ErpStaffLeaveRoute: ErpStaffLeaveRoute,
  ErpStaffStudentsRoute: ErpStaffStudentsRoute,
}

const ErpStaffRouteWithChildren = ErpStaffRoute._addFileChildren(
  ErpStaffRouteChildren,
)

interface ErpRouteRouteChildren {
  ErpAssignmentRoute: typeof ErpAssignmentRoute
  ErpBookVerificationFormRoute: typeof ErpBookVerificationFormRoute
  ErpDashboardRoute: typeof ErpDashboardRoute
  ErpFeesRoute: typeof ErpFeesRoute
  ErpHodRoute: typeof ErpHodRouteWithChildren
  ErpLeaveRoute: typeof ErpLeaveRoute
  ErpLeaveRequestsRoute: typeof ErpLeaveRequestsRoute
  ErpLoginRoute: typeof ErpLoginRoute
  ErpNoticesRoute: typeof ErpNoticesRoute
  ErpPasswordRoute: typeof ErpPasswordRoute
  ErpProfileRoute: typeof ErpProfileRoute
  ErpResultsRoute: typeof ErpResultsRoute
  ErpStaffRoute: typeof ErpStaffRouteWithChildren
  ErpTimetableRoute: typeof ErpTimetableRoute
}

const ErpRouteRouteChildren: ErpRouteRouteChildren = {
  ErpAssignmentRoute: ErpAssignmentRoute,
  ErpBookVerificationFormRoute: ErpBookVerificationFormRoute,
  ErpDashboardRoute: ErpDashboardRoute,
  ErpFeesRoute: ErpFeesRoute,
  ErpHodRoute: ErpHodRouteWithChildren,
  ErpLeaveRoute: ErpLeaveRoute,
  ErpLeaveRequestsRoute: ErpLeaveRequestsRoute,
  ErpLoginRoute: ErpLoginRoute,
  ErpNoticesRoute: ErpNoticesRoute,
  ErpPasswordRoute: ErpPasswordRoute,
  ErpProfileRoute: ErpProfileRoute,
  ErpResultsRoute: ErpResultsRoute,
  ErpStaffRoute: ErpStaffRouteWithChildren,
  ErpTimetableRoute: ErpTimetableRoute,
}

const ErpRouteRouteWithChildren = ErpRouteRoute._addFileChildren(
  ErpRouteRouteChildren,
)

interface CoeRouteChildren {
  CoeLoginRoute: typeof CoeLoginRoute
  CoePortalRoute: typeof CoePortalRoute
  CoeResultsRoute: typeof CoeResultsRoute
}

const CoeRouteChildren: CoeRouteChildren = {
  CoeLoginRoute: CoeLoginRoute,
  CoePortalRoute: CoePortalRoute,
  CoeResultsRoute: CoeResultsRoute,
}

const CoeRouteWithChildren = CoeRoute._addFileChildren(CoeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErpRouteRoute: ErpRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CampusRoute: CampusRoute,
  CampusNavigationRoute: CampusNavigationRoute,
  CoeRoute: CoeRouteWithChildren,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  FacilitiesRoute: FacilitiesRoute,
  FacultyRoute: FacultyRoute,
  FacultyDirectoryRoute: FacultyDirectoryRoute,
  MenuRoute: MenuRoute,
  NoticesRoute: NoticesRoute,
  LoginHodRoute: LoginHodRoute,
  LoginStaffRoute: LoginStaffRoute,
  LoginStudentRoute: LoginStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
